[workspace]
resolver = "2"
members = [
  "crates/newengine-core",
  "crates/newengine-platform-winit",
  "crates/newengine-modules-window-winit",
  "crates/newengine-modules-cef",
  "crates/newengine-modules-logging",
  "apps/editor",
]

[workspace.package]
edition = "2021"
license = "Proprietary"
