[package]
name = "input"
version = "0.1.2"
edition = "2021"
description = "NewEngine input plugin (DLL): listens to host events and provides InputApiV1"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
abi_stable = "0.11"
newengine-plugin-api = { path = "../newengine-plugin-api" }